package httpserver

import (
	"time"

	"family_teacher_remote/internal/httpserver/handlers"
	"family_teacher_remote/internal/httpserver/middleware"

	"github.com/gofiber/fiber/v2"
)

func registerRoutes(app *fiber.App, deps handlers.Dependencies) {
	health := handlers.NewHealthHandler()
	auth := handlers.NewAuthHandler(deps)
	bundles := handlers.NewBundlesHandler(deps)
	catalog := handlers.NewCatalogHandler(deps)
	enrollments := handlers.NewEnrollmentHandler(deps)
	moderation := handlers.NewModerationHandler(deps)
	studyMode := handlers.NewStudyModeHandler(deps)
	accountDevices := handlers.NewAccountDevicesHandler(deps)
	teacherCourses := handlers.NewTeacherCoursesHandler(deps)
	artifactSync := handlers.NewArtifactSyncHandler(deps)

	app.Get("/health", health.Check)

	api := app.Group("/api")
	authLimiterRegister := middleware.NewRateLimiter(5, time.Minute)
	authLimiterLogin := middleware.NewRateLimiter(10, time.Minute)
	authLimiterRecovery := middleware.NewRateLimiter(3, time.Minute)
	authLimiterChange := middleware.NewRateLimiter(5, time.Minute)
	authLimiterRefresh := middleware.NewRateLimiter(20, time.Minute)
	catalogLimiter := middleware.NewRateLimiter(60, time.Minute)
	enrollmentLimiter := middleware.NewRateLimiter(20, time.Minute)
	syncLimiter := middleware.NewRateLimiter(300, time.Minute)

	api.Post("/auth/register", authLimiterRegister.Handler(middleware.KeyByIP), auth.Register)
	api.Post("/auth/register-student", authLimiterRegister.Handler(middleware.KeyByIP), auth.RegisterStudent)
	api.Post("/auth/register-teacher", authLimiterRegister.Handler(middleware.KeyByIP), auth.RegisterTeacher)
	api.Post("/auth/login", authLimiterLogin.Handler(middleware.KeyByIP), auth.Login)
	api.Post("/auth/change-password", authLimiterChange.Handler(middleware.KeyByIP), auth.ChangePassword)
	api.Post("/auth/request-recovery", authLimiterRecovery.Handler(middleware.KeyByIP), auth.RequestRecovery)
	api.Post("/auth/reset-password", authLimiterRecovery.Handler(middleware.KeyByIP), auth.ResetPassword)
	api.Post("/auth/refresh", authLimiterRefresh.Handler(middleware.KeyByIP), auth.Refresh)
	api.Post("/auth/revoke", authLimiterRefresh.Handler(middleware.KeyByIP), auth.Revoke)
	api.Use(middleware.NewAuthContext(deps.Config.JWTVerifySecrets, deps.Store.DB).Handler)
	api.Post("/bundles/upload", bundles.Upload)
	api.Get("/bundles/download", bundles.Download)
	api.Get("/bundles/latest-info", bundles.GetLatestCourseBundleInfo)

	api.Get("/catalog/teachers", catalogLimiter.Handler(middleware.KeyByIP), catalog.ListTeachers)
	api.Get("/catalog/courses", catalogLimiter.Handler(middleware.KeyByIP), catalog.ListCourses)
	api.Get("/subject-labels", catalogLimiter.Handler(middleware.KeyByIP), moderation.ListAvailableSubjectLabels)

	api.Get("/account/profile", auth.GetAccountProfile)
	api.Post("/account/recovery-email", authLimiterChange.Handler(middleware.KeyByIP), auth.UpdateRecoveryEmail)
	api.Get("/account/devices", accountDevices.ListAccountDevices)
	api.Post("/account/devices/:deviceKey/delete", accountDevices.DeleteAccountDevice)
	api.Get("/teacher/courses", teacherCourses.ListCourses)
	api.Get("/teacher/control-pin/status", studyMode.GetTeacherControlPinStatus)
	api.Post("/teacher/control-pin", studyMode.UpsertTeacherControlPin)
	api.Get("/teacher/student-devices", studyMode.ListTeacherStudentDevices)
	api.Post("/teacher/students/:studentUserId/study-mode/override", studyMode.UpsertStudyModeOverride)
	api.Get("/teacher/students/:studentUserId/study-mode/schedules", studyMode.ListStudyModeSchedules)
	api.Post("/teacher/students/:studentUserId/study-mode/schedules", studyMode.CreateStudyModeSchedule)
	api.Post("/teacher/students/:studentUserId/study-mode/schedules/:id/delete", studyMode.DeleteStudyModeSchedule)
	api.Post("/teacher/courses", teacherCourses.CreateCourse)
	api.Post("/teacher/courses/:id/metadata", teacherCourses.UpdateCourseMetadata)
	api.Post("/teacher/courses/:id/subject-labels", teacherCourses.UpdateCourseSubjectLabels)
	api.Post("/teacher/courses/:id/publish", teacherCourses.PublishCourse)
	api.Post("/teacher/courses/:id/delete", teacherCourses.DeleteCourse)
	api.Post("/teacher/courses/:id/bundles", teacherCourses.EnsureBundle)
	api.Get("/teacher/courses/:id/bundle-versions", bundles.ListTeacherCourseBundleVersions)
	api.Post("/teacher/courses/:id/bundle-versions/:versionId/delete", bundles.DeleteTeacherCourseBundleVersion)

	api.Post("/enrollment-requests", enrollmentLimiter.Handler(middleware.KeyByIP), enrollments.CreateRequest)
	api.Get("/enrollment-requests", enrollments.ListStudentRequests)
	api.Get("/enrollments", enrollments.ListEnrollments)
	api.Post("/enrollments/:id/quit-request", enrollmentLimiter.Handler(middleware.KeyByIP), enrollments.CreateQuitRequest)
	api.Get("/enrollments/quit-requests", enrollments.ListStudentQuitRequests)
	api.Post("/student/device/heartbeat", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), studyMode.HeartbeatStudentDevice)
	api.Post("/student/study-mode/verify-control-pin", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), studyMode.VerifyStudentStudyModeControlPin)
	api.Get("/teacher/enrollments", enrollments.ListTeacherEnrollments)
	api.Get("/teacher/enrollment-requests", enrollments.ListTeacherRequests)
	api.Post("/teacher/enrollment-requests/:id/approve", enrollments.ApproveRequest)
	api.Post("/teacher/enrollment-requests/:id/reject", enrollments.RejectRequest)
	api.Get("/teacher/quit-requests", enrollments.ListTeacherQuitRequests)
	api.Post("/teacher/quit-requests/:id/approve", enrollments.ApproveQuitRequest)
	api.Post("/teacher/quit-requests/:id/reject", enrollments.RejectQuitRequest)
	api.Get("/subject-admin/teacher-registration-requests", moderation.ListSubjectAdminTeacherRegistrationRequests)
	api.Post("/subject-admin/teacher-registration-requests/:id/approve", moderation.ApproveTeacherRegistration)
	api.Post("/subject-admin/teacher-registration-requests/:id/reject", moderation.RejectTeacherRegistration)
	api.Get("/subject-admin/course-upload-requests", moderation.ListSubjectAdminCourseUploadRequests)
	api.Post("/subject-admin/course-upload-requests/:id/approve", moderation.ApproveCourseUpload)
	api.Post("/subject-admin/course-upload-requests/:id/reject", moderation.RejectCourseUpload)

	api.Get("/admin/users", moderation.ListAdminUsers)
	api.Post("/admin/users/:userId/delete", moderation.DeleteTeacher)
	api.Get("/admin/subject-labels", moderation.ListSubjectLabels)
	api.Post("/admin/subject-labels", moderation.CreateSubjectLabel)
	api.Post("/admin/subject-labels/:id", moderation.UpdateSubjectLabel)
	api.Post("/admin/subject-labels/:id/subject-admins", moderation.AssignSubjectAdmin)
	api.Post("/admin/subject-labels/:id/subject-admins/:userId/delete", moderation.RemoveSubjectAdmin)
	api.Get("/admin/teacher-registration-requests", moderation.ListAdminTeacherRegistrationRequests)
	api.Post("/admin/teacher-registration-requests/:id/approve", moderation.ApproveTeacherRegistration)
	api.Post("/admin/teacher-registration-requests/:id/reject", moderation.RejectTeacherRegistration)
	api.Get("/admin/course-upload-requests", moderation.ListAdminCourseUploadRequests)
	api.Post("/admin/course-upload-requests/:id/approve", moderation.ApproveCourseUpload)
	api.Post("/admin/course-upload-requests/:id/reject", moderation.RejectCourseUpload)

	api.Get("/artifacts/sync/state2", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), artifactSync.State2)
	api.Get("/artifacts/sync/state1", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), artifactSync.State1)
	api.Get("/artifacts/download", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), artifactSync.Download)
	api.Post("/artifacts/download-batch", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), artifactSync.DownloadBatch)
	api.Post("/artifacts/upload-batch", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), artifactSync.UploadBatch)
	api.Post("/artifacts/upload", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), artifactSync.Upload)
	api.Post("/artifacts/delete", syncLimiter.Handler(middleware.KeyByAuthDeviceOrIP), artifactSync.Delete)
}
