CREATE TABLE teacher_course_sync_state2 (
  user_id BIGINT NOT NULL PRIMARY KEY,
  state2 VARCHAR(191) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE student_enrollment_sync_state2 (
  user_id BIGINT NOT NULL PRIMARY KEY,
  state2 VARCHAR(191) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
